"""Detect AI-generated risky code patterns, placeholders, and unfinished work."""
from __future__ import annotations
import re
from pathlib import Path
from typing import Iterable, List

from ..severity import Finding, Severity

# (regex, severity, title, category)
AI_PATTERNS: list[tuple[re.Pattern, Severity, str, str]] = [
    (re.compile(r"\byour\s+code\s+here\b", re.I), Severity.HIGH, "Placeholder: 'your code here'", "placeholder"),
    (re.compile(r"\binsert\s+secret\s+here\b", re.I), Severity.CRITICAL, "Placeholder: 'insert secret here'", "placeholder"),
    (re.compile(r"\breplace\s+this\b", re.I), Severity.MEDIUM, "Placeholder: 'replace this'", "placeholder"),
    (re.compile(r"\bfill\s+this\b", re.I), Severity.MEDIUM, "Placeholder: 'fill this'", "placeholder"),
    (re.compile(r"for\s+illustration\s+purposes", re.I), Severity.MEDIUM, "Illustrative-only code marker", "ai_marker"),
    (re.compile(r"as\s+an\s+ai\s+language\s+model", re.I), Severity.HIGH, "AI assistant disclaimer leaked into source", "ai_marker"),
    (re.compile(r"generated\s+by\s+(chat)?gpt", re.I), Severity.HIGH, "AI authorship marker", "ai_marker"),
    (re.compile(r"sure[,!]?\s+here\s+is\s+the\s+code", re.I), Severity.HIGH, "Chat preamble leaked into source", "ai_marker"),
    (re.compile(r"```(?:python|js|ts|bash|json)?\s*$", re.M), Severity.HIGH, "Markdown code fence leaked into source", "leaked_markdown"),
    (re.compile(r"#\s*TODO[: ]+(implement|finish|complete|placeholder|fixme)", re.I), Severity.MEDIUM, "Suspicious TODO placeholder", "todo"),
    (re.compile(r"#\s*FIXME", re.I), Severity.LOW, "FIXME comment", "todo"),
    (re.compile(r"\bpass\s*#\s*(implement|todo|placeholder)", re.I), Severity.HIGH, "Unfinished implementation (pass + TODO)", "unfinished"),
    (re.compile(r"raise\s+NotImplementedError", re.I), Severity.MEDIUM, "Unfinished implementation (NotImplementedError)", "unfinished"),
    (re.compile(r"#\s*(autogenerated|auto-generated|do\s+not\s+edit)", re.I), Severity.LOW, "Autogenerated marker comment", "ai_marker"),
    (re.compile(r"['\"]sk-[A-Za-z0-9]{20,}['\"]"), Severity.CRITICAL, "Hardcoded API key (OpenAI-style)", "hardcoded_secret"),
    (re.compile(r"['\"]xox[baprs]-[A-Za-z0-9-]{10,}['\"]"), Severity.CRITICAL, "Hardcoded Slack token", "hardcoded_secret"),
    (re.compile(r"['\"]ghp_[A-Za-z0-9]{30,}['\"]"), Severity.CRITICAL, "Hardcoded GitHub PAT", "hardcoded_secret"),
    (re.compile(r"['\"]AKIA[0-9A-Z]{16}['\"]"), Severity.CRITICAL, "Hardcoded AWS access key", "hardcoded_secret"),
    (re.compile(r"\b(API_?KEY|SECRET|PASSWORD|TOKEN)\s*=\s*['\"][^'\"]{8,}['\"]"), Severity.HIGH, "Possible hardcoded credential", "hardcoded_secret"),
    (re.compile(r"['\"]fake[-_]?(secret|key|token)['\"]", re.I), Severity.MEDIUM, "Fake/demo secret literal", "hardcoded_secret"),
]

DEFAULT_EXTS = {".py", ".js", ".ts", ".tsx", ".jsx", ".go", ".rb", ".java", ".rs"}


class AIPatternScanner:
    name = "ai_patterns"

    def __init__(self, extensions: Iterable[str] = DEFAULT_EXTS):
        self.extensions = set(extensions)

    def scan(self, root: Path) -> List[Finding]:
        findings: list[Finding] = []
        for path in self._walk(root):
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for i, line in enumerate(text.splitlines(), start=1):
                for pattern, sev, title, cat in AI_PATTERNS:
                    if pattern.search(line):
                        findings.append(Finding(
                            scanner=self.name,
                            category=cat,
                            severity=sev,
                            title=title,
                            description=f"Pattern matched in {path}",
                            file=str(path),
                            line=i,
                            snippet=line.strip()[:200],
                        ))
        return findings

    def _walk(self, root: Path):
        skip = {".git", "node_modules", ".venv", "venv", "__pycache__", "reports", "dist", "build"}
        for p in root.rglob("*"):
            if any(part in skip for part in p.parts):
                continue
            if p.is_file() and p.suffix in self.extensions:
                yield p
